import { useState } from 'react'

export default function RobotsTxt() {
  const [site, setSite] = useState('https://example.com')
  const [allow, setAllow] = useState('/\n/assets/')
  const [disallow, setDisallow] = useState('/admin\n/private\n/checkout')
  const [sitemap, setSitemap] = useState('https://example.com/sitemap.xml')
  const [rules, setRules] = useState([{ ua: '*', allow: '', disallow: '/admin' }])
  const [crawlDelay, setCrawlDelay] = useState('')

  const gen = () => {
    const l: string[] = []
    l.push(`# robots.txt generated by NutterTools`)
    l.push(`User-agent: *`)
    l.push(`Disallow: /admin`)
    l.push(`Disallow: /private`)
    l.push(`Allow: /`)
    if (crawlDelay) l.push(`Crawl-delay: ${crawlDelay}`)
    l.push('')
    if (sitemap) l.push(`Sitemap: ${sitemap}`)
    return l.join('\n')
  }

  return (
    <div className="space-y-4 max-w-2xl">
      <input value={site} onChange={e => setSite(e.target.value)} className="w-full border px-3 h-9 text-sm" placeholder="https://example.com" />
      <div className="grid sm:grid-cols-2 gap-3">
        <label className="text-sm font-semibold">Allow (one per line)<textarea value={allow} onChange={e => setAllow(e.target.value)} className="w-full border p-2 h-24 mt-1 font-mono text-xs" /></label>
        <label className="text-sm font-semibold">Disallow (one per line)<textarea value={disallow} onChange={e => setDisallow(e.target.value)} className="w-full border p-2 h-24 mt-1 font-mono text-xs" /></label>
      </div>
      <input value={sitemap} onChange={e => setSitemap(e.target.value)} className="w-full border px-3 h-9 text-sm" placeholder="Sitemap URL" />
      <div className="flex items-center gap-3">
        <label className="text-sm">Crawl delay (optional)
          <input value={crawlDelay} onChange={e => setCrawlDelay(e.target.value)} className="border px-3 h-9 ml-2 w-20 text-sm" /></label>
        <button onClick={() => navigator.clipboard.writeText(gen())} className="px-4 h-9 bg-white text-zinc-900 ring-1 ring-zinc-300 dark:ring-zinc-600 text-sm ml-auto">Copy</button>
        <a href={`data:text/plain;charset=utf-8,${encodeURIComponent(gen())}`} download="robots.txt" className="px-4 h-9 border text-sm inline-flex items-center">Download</a>
      </div>
      <textarea value={gen()} readOnly className="w-full h-48 border p-3 font-mono text-xs bg-zinc-50 dark:bg-zinc-800" />
    </div>
  )
}
