import {
  AirVent, AppWindow, Apple, ArrowRightLeft, AudioLines, AudioWaveform, BadgeCheck, Barcode, Binary,
  BookMarked, BookOpen, Bot, Braces, Briefcase, CalendarDays, Camera, Captions, CaseUpper, ChefHat,
  CircleDot, Clapperboard, Clock, Clock3, Code, Coins, Combine, Contrast, Copy, Cpu, CreditCard, Crop,
  Database, Dice5, Diff, Dices, DollarSign, Droplets, Earth, Eraser,
  Eye, EyeOff, Feather, FileArchive, FileCode, FileCode2, FileCog, FileDown, FileImage, FileJson,
  FileOutput, FilePlus, FileSearch, FileSignature, FileSpreadsheet, FileText, FileType, FileUp, FileVideo,
  Files, Film, Fingerprint, Flame, FolderArchive, Frame, Gauge, Ghost, GitBranch, Globe, GraduationCap,
  HardDrive, Hash, Highlighter, History, Home, IdCard, Image as ImageIcon, ImagePlus, Images, Keyboard, KeyRound,
  KeySquare, Landmark, Languages, Layers, Link, Link2, ListChecks, ListOrdered, ListTree, Lock, LockKeyhole,
  Mail, MailCheck, Maximize2, MessagesSquare, Mic, Mic2, Minimize2, Monitor, Moon, MousePointer2, Music,
  Music2, Network, NotebookPen, NotepadText, PaintBucket, Palette, PanelsTopLeft, Pen, PenLine, Pencil, Percent,
  Pipette, QrCode, Radar, Radio, RadioTower, Rainbow, Receipt, RefreshCw, Regex, Repeat, Repeat2, Rewind,
  Rotate3d, RotateCcw, RotateCw, Ruler, ScanQrCode, ScanText, Scissors, ScrollText, Search, Server,
  Shapes, Share2, Sheet, Shield, ShieldAlert, ShieldCheck, ShieldX, Shuffle, Sigma, Slice, SlidersHorizontal,
  Smile, SmilePlus, Speaker, Sparkles, SpellCheck, Split, Stamp, Subtitles, SwatchBook, Table, Table2,
  Tags, Terminal, Text, TextQuote, TextCursorInput, Timer, TrendingUp, Turtle, Type, Undo2, User,
  Users, Video, VolumeX, Wand2, WandSparkles, Waypoints, Waves, Weight, Wind, Workflow, Wrench, Zap, ZoomIn,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

const TOOL_ICONS: Record<string, LucideIcon> = {
  'image-compressor': Minimize2,
  'heic-to-jpg': Apple,
  'format-converter': Repeat,
  'image-ocr': ScanText,
  'bg-remover': Wand2,
  'qr-generator': QrCode,
  'image-resizer': Maximize2,
  'image-cropper': Crop,
  'image-filters': SlidersHorizontal,
  'merge-pdf': Combine,
  'split-pdf': Scissors,
  'images-to-pdf': FileImage,
  'pdf-to-images': FileOutput,
  'compress-pdf': FileDown,
  'rotate-pdf': RotateCw,
  'pdf-text-extract': FileSearch,
  'pdf-page-numbers': ListOrdered,
  'pdf-watermark': Droplets,
  'pdf-protect': Lock,
  'word-to-pdf': FileType,
  'pdf-to-word': FileUp,
  'pdf-viewer': BookOpen,
  'json-formatter': Braces,
  'regex-tester': Regex,
  'jwt-tool': IdCard,
  'html-jsx': FileCode,
  'css-tailwind': Wind,
  'minify-beautify': Sparkles,
  'cron-generator': Clock,
  'hash-generator': Hash,
  'uuid-generator': Fingerprint,
  'env-generator': FileCog,
  'readme-generator': BookMarked,
  'curl-to-fetch': Terminal,
  'chmod-calc': Shield,
  'yaml-json': ArrowRightLeft,
  'html-preview': Eye,
  'sql-formatter': Database,
  'base64-tool': Binary,
  'password-generator': KeyRound,
  'bcrypt-tool': LockKeyhole,
  'url-encoder': Link,
  'morse-code': AudioWaveform,
  'binary-converter': Sigma,
  'caesar-cipher': RotateCcw,
  'text-encryptor': ShieldCheck,
  'word-counter': Type,
  'case-converter': CaseUpper,
  'dedupe-lines': Copy,
  'tts-stt': Speaker,
  'lorem-generator': TextQuote,
  'markdown-editor': FileText,
  'diff-checker': Diff,
  'slug-generator': Link2,
  'whitespace-cleaner': Eraser,
  'invoice-generator': Receipt,
  'resume-builder': Briefcase,
  'text-reverser': Undo2,
  'emoji-remover': Ghost,
  'palette-extractor': Palette,
  'color-picker': Pipette,
  'hex-rgb': PaintBucket,
  'gradient-generator': Rainbow,
  'shadow-generator': Shapes,
  'contrast-checker': Contrast,
  'blob-maker': Waves,
  'css-color-converter': SwatchBook,
  'color-shades': CircleDot,
  'video-compressor': FileVideo,
  'video-to-mp3': Music,
  'video-to-gif': Film,
  'mp4-to-webm': Repeat2,
  'video-trimmer': Slice,
  'video-muter': VolumeX,
  'video-rotator': Rotate3d,
  'video-speed': Gauge,
  'gif-to-video': Clapperboard,
  'audio-converter': AudioLines,
  'audio-trimmer': Music2,
  'voice-recorder': Mic,
  'audio-transcriber': Captions,
  'tone-generator': Radio,
  'csv-json': Table2,
  'excel-to-pdf': FileSpreadsheet,
  'zip-tool': FileArchive,
  'bulk-renamer': PenLine,
  'txt-to-pdf': FilePlus,
  'meta-generator': Tags,
  'og-previewer': Monitor,
  'og-generator': ImagePlus,
  'sitemap-gen': Network,
  'utm-builder': Share2,
  'ip-info': Globe,
  'robots-txt': Bot,
  'http-status': Server,
  'unit-converter': Ruler,
  'age-calc': CalendarDays,
  'percent-calc': Percent,
  'screen-recorder': Camera,
  'typing-test': Keyboard,
  'pomodoro': Timer,
  'bmi-calculator': Weight,
  'tip-calculator': Coins,
  'random-number': Dices,
  'image-upscaler': ZoomIn,
  'image-captioner': SmilePlus,
  'summarizer': ScrollText,
  'translator': Languages,
  'sentiment': Smile,
  'recipe-generator': ChefHat,
  'poem-generator': Feather,
  'llm-token-counter': Cpu,
  'json-yaml': FileJson,
  'json-csv': Table,
  'json-schema-validator': BadgeCheck,
  'csv-sql': Layers,
  'graphql-formatter': GitBranch,
  'hmac-generator': KeySquare,
  'html-entity-encoder': TextCursorInput,
  'file-hash': Files,
  'email-validator': MailCheck,
  'card-validator': CreditCard,
  'bin-lookup': Landmark,
  'markdown-html': FileCode2,
  'toc-generator': ListTree,
  'reading-time': Clock3,
  'keyword-density': Search,
  'paraphraser': Pencil,
  'photo-caption': Pen,
  'metadata-remover': ShieldX,
  'favicon-generator': AppWindow,
  'face-blur': EyeOff,
  'pdf-to-excel': Sheet,
  'pdf-annotator': Highlighter,
  'pdf-crop': Frame,
  'pdf-form-flattener': Stamp,
  'video-reverser': History,
  'video-bg-remover': WandSparkles,
  'burn-subtitles': Subtitles,
  'audio-enhancer': Zap,
  'audio-noise-remover': AirVent,
  'stem-splitter': Split,
  'audio-reverser': Rewind,
  'speed-pitch': Turtle,
  'voice-changer': Mic2,
  'llmstxt': NotebookPen,
  'dns-lookup': RadioTower,
  'whois-lookup': User,
  'cidr-calculator': Workflow,
  'email-signature': Mail,
  'batch-qr': ScanQrCode,
  'compound-interest': TrendingUp,
  'mortgage-calculator': Home,
  'gpa-calculator': GraduationCap,
  'dice-roller': Dice5,
  'barcode-generator': Barcode,
  'timezone-converter': Earth,
  'password-strength': ShieldAlert,
  'grammar-checker': SpellCheck,
  'cover-letter': FileSignature,
  'memo-writer': NotepadText,
  'ai-content-detector': Radar,
  'hashtag-generator': Tags,
  'caption-generator': MessagesSquare,
  'mindmap-generator': Waypoints,
  'alt-text-generator': Images,
  'xml-formatter': Code,
  'keycode-info': Keyboard,
  'base-converter': Binary,
  'flexbox-generator': PanelsTopLeft,
  'cron-parser': Clock,
  'css-cursors': MousePointer2,
  'timestamp-converter': Clock3,
  'random-picker': ListChecks,
  'yes-no': Shuffle,
  'team-generator': Users,
  'username-generator': User,
  'roman-numeral': Sigma,
  'discount-calculator': Percent,
  'calorie-calculator': Flame,
  'sleep-cycle-calculator': Moon,
  'would-you-rather': MessagesSquare,
  'movie-picker': Film,
  'spin-wheel': RefreshCw,
  'currency-converter': DollarSign,
  'credit-card-generator': CreditCard,
  'qr-scanner': ScanQrCode,
  'image-to-base64': ImageIcon,
  'palindrome-checker': Repeat,
  'markdown-table-generator': Table,
  'file-size-converter': HardDrive,
  'pdf-organizer': Files,
  'pdf-inspector': FileSearch,
}

const CAT_ICONS: Record<string, LucideIcon> = {
  'image-tools': ImageIcon,
  'pdf-tools': FileText,
  'developer-tools': Code,
  'encoding-security': Lock,
  'text-writing': PenLine,
  'color-design': Palette,
  'video-tools': Video,
  'audio-tools': Music,
  'file-tools': FolderArchive,
  'web-seo': Globe,
  'everyday-utilities': Wrench,
  'ai-tools': Sparkles,
}

export function ToolIcon({ id, className }: { id: string, className?: string }) {
  const C = TOOL_ICONS[id] || Wrench
  return <C className={className} strokeWidth={1.9} aria-hidden="true" />
}

export function CategoryIcon({ slug, className }: { slug: string, className?: string }) {
  const C = CAT_ICONS[slug] || Wrench
  return <C className={className} strokeWidth={1.9} aria-hidden="true" />
}

const base = new URL(import.meta.env.BASE_URL, window.location.href).toString()
const ICON_V = 2

export const toolIconUrl = (id: string) => `${base}icons/${id}.png?v=${ICON_V}`

export const catIconUrl = (slug: string) => `${base}icons/cat-${slug}.png?v=${ICON_V}`

export const whiteToolIconUrl = (id: string) => `${base}icons/white/${id}.png?v=${ICON_V}`

export const whiteCatIconUrl = (slug: string) => `${base}icons/white/cat-${slug}.png?v=${ICON_V}`

export function CutoutToolIcon({ id, className, tone }: { id: string, className?: string, tone?: string }) {
  return <img src={toolIconUrl(id)} alt="" className={className} draggable={false} />
}

export function CutoutCategoryIcon({ slug, className, tone }: { slug: string, className?: string, tone?: string }) {
  return <img src={catIconUrl(slug)} alt="" className={className} draggable={false} />
}
