import { useState } from 'react'
import {
  AirVent, AppWindow, Apple, ArrowDownWideNarrow, ArrowRightLeft, AudioLines, AudioWaveform, BadgeCheck,
  Barcode, Battery, Beef, Binary, Blocks, BookMarked, BookOpen, Bot, Box, Braces, Briefcase, Cable, Cake,
  Calculator, CalendarDays, Camera, Captions, CaseUpper, ChefHat, CircleDot, Clapperboard, Clock, Clock3,
  CloudRain, Code, Coffee, Coins, Combine, Contrast, CookingPot, Copy, Cpu, CreditCard, Croissant, Crop,
  Database, Dice5, Diff, Dices, DollarSign, Droplets, Earth, Eraser,
  Eye, EyeOff, Fan, Feather, Fence, FileArchive, FileCode, FileCode2, FileCog, FileDown, FileImage, FileJson,
  FileOutput, FilePlus, FileSearch, FileSignature, FileSpreadsheet, FileText, FileType, FileUp, FileVideo,
  Files, Film, Fingerprint, Fish, Flame, FlaskConical, FolderArchive, Frame, Fuel, Gauge, Ghost, GitBranch,
  Globe, GraduationCap, Grid3x3, Hammer, HardDrive, Hash, Highlighter, History, Home, Hourglass, IdCard,
  Image as ImageIcon, ImagePlus, Images, Keyboard, KeyRound,
  KeySquare, Landmark, Languages, Layers, LayoutGrid, Leaf, Lightbulb, Link, Link2, ListChecks, ListOrdered,
  ListTree, Lock, LockKeyhole,
  Mail, MailCheck, Martini, Maximize2, MessagesSquare, Mic, Mic2, Minimize2, Monitor, Moon, Mountain,
  MousePointer2, MoveVertical, Music,
  Music2, Network, NotebookPen, NotepadText, PaintBucket, Palette, PanelsTopLeft, Pen, PenLine, Pencil, Percent,
  Pipette, Pizza, Plug, PlugZap, Projector, QrCode, Radar, Radio, RadioTower, Rainbow, Receipt, RefreshCw,
  Regex, Repeat, Repeat2, Rewind, Road, Rotate3d, RotateCcw, RotateCw, Rows3, Ruler, ScanQrCode, ScanText,
  Scissors, ScrollText, Search, Server, Shapes, Share2, Sheet, Shield, ShieldAlert, ShieldCheck, ShieldX,
  ShoppingBag, Shuffle, Sigma, Slice, SlidersHorizontal, Smile, SmilePlus, Snowflake, Speaker, Sparkles,
  SpellCheck, Split, Sprout, Stamp, Subtitles, Sun, SwatchBook, Swords, Table, Table2,
  Tags, Tag, Terminal, Text, TextQuote, TextCursorInput, Thermometer, Timer, Trees, TrendingUp, Turtle, Tv, Type,
  Undo2, User, Users, Video, VolumeX, Wallet, Wand2, WandSparkles, Warehouse, Waves, Waypoints, Weight, Wheat,
  Wind, Workflow, Wrench, Zap, ZoomIn,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const TOOL_ICONS: Record<string, LucideIcon> = {
  'image-compressor': Minimize2,
  'heic-to-jpg': Apple,
  'format-converter': Repeat,
  'image-ocr': ScanText,
  'bg-remover': Wand2,
  'qr-generator': QrCode,
  'image-resizer': Maximize2,
  'image-cropper': Crop,
  'image-filters': SlidersHorizontal,
  'merge-pdf': Combine,
  'split-pdf': Scissors,
  'images-to-pdf': FileImage,
  'pdf-to-images': FileOutput,
  'compress-pdf': FileDown,
  'rotate-pdf': RotateCw,
  'pdf-text-extract': FileSearch,
  'pdf-page-numbers': ListOrdered,
  'pdf-watermark': Droplets,
  'pdf-protect': Lock,
  'word-to-pdf': FileType,
  'pdf-to-word': FileUp,
  'pdf-viewer': BookOpen,
  'json-formatter': Braces,
  'regex-tester': Regex,
  'jwt-tool': IdCard,
  'html-jsx': FileCode,
  'css-tailwind': Wind,
  'minify-beautify': Sparkles,
  'cron-generator': Clock,
  'hash-generator': Hash,
  'uuid-generator': Fingerprint,
  'env-generator': FileCog,
  'readme-generator': BookMarked,
  'curl-to-fetch': Terminal,
  'chmod-calc': Shield,
  'yaml-json': ArrowRightLeft,
  'html-preview': Eye,
  'sql-formatter': Database,
  'base64-tool': Binary,
  'password-generator': KeyRound,
  'bcrypt-tool': LockKeyhole,
  'url-encoder': Link,
  'morse-code': AudioWaveform,
  'binary-converter': Sigma,
  'caesar-cipher': RotateCcw,
  'text-encryptor': ShieldCheck,
  'word-counter': Type,
  'case-converter': CaseUpper,
  'dedupe-lines': Copy,
  'tts-stt': Speaker,
  'lorem-generator': TextQuote,
  'markdown-editor': FileText,
  'diff-checker': Diff,
  'slug-generator': Link2,
  'whitespace-cleaner': Eraser,
  'invoice-generator': Receipt,
  'resume-builder': Briefcase,
  'text-reverser': Undo2,
  'emoji-remover': Ghost,
  'palette-extractor': Palette,
  'color-picker': Pipette,
  'hex-rgb': PaintBucket,
  'gradient-generator': Rainbow,
  'shadow-generator': Shapes,
  'contrast-checker': Contrast,
  'blob-maker': Waves,
  'css-color-converter': SwatchBook,
  'color-shades': CircleDot,
  'video-compressor': FileVideo,
  'video-to-mp3': Music,
  'video-to-gif': Film,
  'mp4-to-webm': Repeat2,
  'video-trimmer': Slice,
  'video-muter': VolumeX,
  'video-rotator': Rotate3d,
  'video-speed': Gauge,
  'gif-to-video': Clapperboard,
  'audio-converter': AudioLines,
  'audio-trimmer': Music2,
  'voice-recorder': Mic,
  'audio-transcriber': Captions,
  'tone-generator': Radio,
  'csv-json': Table2,
  'excel-to-pdf': FileSpreadsheet,
  'zip-tool': FileArchive,
  'bulk-renamer': PenLine,
  'txt-to-pdf': FilePlus,
  'meta-generator': Tags,
  'og-previewer': Monitor,
  'og-generator': ImagePlus,
  'sitemap-gen': Network,
  'utm-builder': Share2,
  'ip-info': Globe,
  'robots-txt': Bot,
  'http-status': Server,
  'unit-converter': Ruler,
  'age-calc': CalendarDays,
  'percent-calc': Percent,
  'screen-recorder': Camera,
  'typing-test': Keyboard,
  'pomodoro': Timer,
  'bmi-calculator': Weight,
  'tip-calculator': Coins,
  'random-number': Dices,
  'image-upscaler': ZoomIn,
  'image-captioner': SmilePlus,
  'summarizer': ScrollText,
  'translator': Languages,
  'sentiment': Smile,
  'recipe-generator': ChefHat,
  'poem-generator': Feather,
  'llm-token-counter': Cpu,
  'json-yaml': FileJson,
  'json-csv': Table,
  'json-schema-validator': BadgeCheck,
  'csv-sql': Layers,
  'graphql-formatter': GitBranch,
  'hmac-generator': KeySquare,
  'html-entity-encoder': TextCursorInput,
  'file-hash': Files,
  'email-validator': MailCheck,
  'card-validator': CreditCard,
  'bin-lookup': Landmark,
  'markdown-html': FileCode2,
  'toc-generator': ListTree,
  'reading-time': Clock3,
  'keyword-density': Search,
  'paraphraser': Pencil,
  'photo-caption': Pen,
  'metadata-remover': ShieldX,
  'favicon-generator': AppWindow,
  'face-blur': EyeOff,
  'pdf-to-excel': Sheet,
  'pdf-annotator': Highlighter,
  'pdf-crop': Frame,
  'pdf-form-flattener': Stamp,
  'video-reverser': History,
  'video-bg-remover': WandSparkles,
  'burn-subtitles': Subtitles,
  'audio-enhancer': Zap,
  'audio-noise-remover': AirVent,
  'stem-splitter': Split,
  'audio-reverser': Rewind,
  'speed-pitch': Turtle,
  'voice-changer': Mic2,
  'llmstxt': NotebookPen,
  'dns-lookup': RadioTower,
  'whois-lookup': User,
  'cidr-calculator': Workflow,
  'email-signature': Mail,
  'batch-qr': ScanQrCode,
  'compound-interest': TrendingUp,
  'mortgage-calculator': Home,
  'gpa-calculator': GraduationCap,
  'dice-roller': Dice5,
  'barcode-generator': Barcode,
  'timezone-converter': Earth,
  'password-strength': ShieldAlert,
  'grammar-checker': SpellCheck,
  'cover-letter': FileSignature,
  'memo-writer': NotepadText,
  'ai-content-detector': Radar,
  'hashtag-generator': Tags,
  'caption-generator': MessagesSquare,
  'mindmap-generator': Waypoints,
  'alt-text-generator': Images,
  'xml-formatter': Code,
  'keycode-info': Keyboard,
  'base-converter': Binary,
  'flexbox-generator': PanelsTopLeft,
  'cron-parser': Clock,
  'css-cursors': MousePointer2,
  'timestamp-converter': Clock3,
  'random-picker': ListChecks,
  'yes-no': Shuffle,
  'team-generator': Users,
  'username-generator': User,
  'roman-numeral': Sigma,
  'discount-calculator': Percent,
  'calorie-calculator': Flame,
  'sleep-cycle-calculator': Moon,
  'would-you-rather': MessagesSquare,
  'movie-picker': Film,
  'spin-wheel': RefreshCw,
  'currency-converter': DollarSign,
  'credit-card-generator': CreditCard,
  'qr-scanner': ScanQrCode,
  'image-to-base64': ImageIcon,
  'palindrome-checker': Repeat,
  'markdown-table-generator': Table,
  'file-size-converter': HardDrive,
  'pdf-organizer': Files,
  'pdf-inspector': FileSearch,
  'subnet-calculator': Network,
  'json-path-tester': Braces,
  'csv-delimiter': Table2,
  'hreflang-generator': Languages,
  'nginx-redirect': ArrowRightLeft,
  'csp-generator': ShieldCheck,
  'px-to-rem': Ruler,
  'aspect-ratio': Frame,
  'readability-score': BookOpen,
  'number-to-words': Sigma,
  'character-counter': Type,
  'loan-calculator': Landmark,
  'sales-tax': Receipt,
  'paypal-fee': Wallet,
  'stripe-fee': CreditCard,
  'etsy-fee': ShoppingBag,
  'ebay-fee': Tag,
  'fuel-trip-cost': Fuel,
  'paint-calculator': PaintBucket,
  'concrete-calculator': Warehouse,
  'gravel-calculator': Mountain,
  'mulch-calculator': Trees,
  'tile-calculator': Grid3x3,
  'drywall-calculator': Layers,
  'fence-calculator': Fence,
  'deck-calculator': Rows3,
  'paver-calculator': Blocks,
  'topsoil-calculator': Sprout,
  'sod-calculator': Leaf,
  'hvac-btu': Thermometer,
  'insulation-calculator': Snowflake,
  'asphalt-calculator': Road,
  'roofing-shingle': Home,
  'board-foot': Ruler,
  'stair-stringer': MoveVertical,
  'stud-wall': LayoutGrid,
  'pipe-volume': Droplets,
  'ramp-slope': TrendingUp,
  'gutter-size': CloudRain,
  'ac-tonnage': Fan,
  'ohms-law': Zap,
  'voltage-drop': ArrowDownWideNarrow,
  'wire-size': Cable,
  'battery-runtime': Battery,
  'tv-distance': Tv,
  'projector-throw': Projector,
  'generator-wattage': PlugZap,
  'solar-panel': Sun,
  'led-resistor': Lightbulb,
  'screen-ppi': Monitor,
  'date-diff': CalendarDays,
  'grade-calculator': GraduationCap,
  'coin-flip': Coins,
  'stopwatch': Timer,
  'countdown-timer': Hourglass,
  'pool-volume': Waves,
  'aquarium-volume': Fish,
  'coffee-ratio': Coffee,
  'rice-water': CookingPot,
  'pizza-dough': Pizza,
  'bread-hydration': Wheat,
  'cake-pan': Cake,
  'yeast-converter': FlaskConical,
  'meat-cooking-time': Beef,
  'dimensional-weight': Box,
  'propane-usage': Flame,
  'cocktail-dilution': Martini,
  'sourdough-calculator': Croissant,
  'dnd-name-generator': Swords,
  'band-name-generator': Music,
  'podcast-name-generator': Mic,
  'clan-name-generator': Shield,
  'csv-viewer': Table,
  'svg-to-png': ImageIcon,
}

const CAT_ICONS: Record<string, LucideIcon> = {
  'image-tools': ImageIcon,
  'pdf-tools': FileText,
  'developer-tools': Code,
  'encoding-security': Lock,
  'text-writing': PenLine,
  'color-design': Palette,
  'video-tools': Video,
  'audio-tools': Music,
  'file-tools': FolderArchive,
  'web-seo': Globe,
  'everyday-utilities': Wrench,
  'ai-tools': Sparkles,
  'calculators': Calculator,
  'building-diy': Hammer,
  'hardware-tech': Plug,
  'name-generators': Wand2,
}

export function ToolIcon({ id, className }: { id: string, className?: string }) {
  const C = TOOL_ICONS[id] || Wrench
  return <C className={className} strokeWidth={1.9} aria-hidden="true" />
}

export function CategoryIcon({ slug, className }: { slug: string, className?: string }) {
  const C = CAT_ICONS[slug] || Wrench
  return <C className={className} strokeWidth={1.9} aria-hidden="true" />
}

const base = new URL(import.meta.env.BASE_URL, window.location.href).toString()
const ICON_V = 2

export const toolIconUrl = (id: string) => `${base}icons/${id}.png?v=${ICON_V}`

export const catIconUrl = (slug: string) => `${base}icons/cat-${slug}.png?v=${ICON_V}`

export const whiteToolIconUrl = (id: string) => `${base}icons/white/${id}.png?v=${ICON_V}`

export const whiteCatIconUrl = (slug: string) => `${base}icons/white/cat-${slug}.png?v=${ICON_V}`

export function CutoutToolIcon({ id, className, tone }: { id: string, className?: string, tone?: string }) {
  const C = TOOL_ICONS[id] || Wrench
  const [broken, setBroken] = useState(false)
  if (broken || !id) return <C className={`${className} ${tone || ''}`} strokeWidth={1.9} aria-hidden="true" />
  return <img src={toolIconUrl(id)} alt="" className={className} draggable={false} onError={() => setBroken(true)} />
}

export function CutoutCategoryIcon({ slug, className, tone }: { slug: string, className?: string, tone?: string }) {
  const C = CAT_ICONS[slug] || Wrench
  const [broken, setBroken] = useState(false)
  if (broken || !slug) return <C className={`${className} ${tone || ''}`} strokeWidth={1.9} aria-hidden="true" />
  return <img src={catIconUrl(slug)} alt="" className={className} draggable={false} onError={() => setBroken(true)} />
}
